### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by kanybekasanbekov** [vsitzmann/deepvoxels#2]
Hello,
Thank you for sharing code.
Which GPU did you use for training this model?
Do you provide trained checkpoints?

**Comment by submagr** [comment]
Hi @kanybekasanbekov ,
I was experimenting with their code. Following are my findings:
GPU Consumption during testing: 2135 MB
GPU Consumption during training: 7527 MB
Please choose a GPU accordingly.

Trained checkpoints: none provided

Hope this helps!

**Comment by vsitzmann** [comment]
Hi! Please excuse the late reply. All training details can be found in the supplement, at the end of the of the arXiv submission: Everything was trained on RTX8000 or RTX 6000 GPUs. I'll publish checkpoints eventually, but upon refactoring the code, the old checkpoints aren't compatible anymore, so I'll have to wait for GPUs in my lab to train new ones...

Thanks for your interest!

**Comment by vsitzmann** [comment]
@submagr thanks for your help!
