### ISSUE TITLE
Depth Scale

### ISSUE THREAD

**Issue by griegler** [vsitzmann/deepvoxels#5]
The dataset contains depth maps in png format. I can read them via `cv2.imread(depth_path, cv2.IMREAD_ANYDEPTH)` and get values in `unit16`. How can I scale the values to get the correct depth?

**Comment by vsitzmann** [comment]
Hi,

the depth is scaled by a factor of 1e4, i.e., to retrieve the original depth, multiply by a factor of 1e-4.

I've also written a minimal example to work with depth, poses, and intrinsics, which you can find in the Google drive in the datasets/ directory.

Best
Vincent
