### ISSUE TITLE
colmap_wrapper.py crash

### ISSUE THREAD

**Issue by feem1** [vsitzmann/deepvoxels#7]
Hello, I was trying to use your wrapper function to generate intrinsics and extrinsics and the code crashed with this error.

Extracting poses
Traceback (most recent call last):
  File "colmap_wrapper.py", line 245, in <module>
    images = read_poses(reconst_dir)
  File "colmap_wrapper.py", line 222, in read_poses
    images = read_images_binary(os.path.join(colmap_workspace, 'sparse', '0', "images.bin"))
  File "colmap_wrapper.py", line 160, in read_images_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: './output/reconstruction/sparse/0/images.bin'

I will try to debug this, but any help is appreciated. Regards.

**Comment by feem1** [comment]
https://stackoverflow.com/questions/49000258/generating-a-pdf-in-ruby-app-on-a-linux-server-qt-qpa-screen-qxcbconnection?rq=1

resolves it.

**Comment by dilaratank** [comment]
I have the same issue and the link did not resolve it for me. Any recommendations?
